<?xml version='1.0' encoding='UTF-8' standalone='yes'?>
<!-- Document definition -->
<!DOCTYPE MEME[
<!ELEMENT MEME (
  training_set,
  model, 
  motifs, 
  scanned_sites_summary?
)>
<!ATTLIST MEME 
  version CDATA #REQUIRED
  release CDATA #REQUIRED
>
<!-- Training-set elements -->
<!ELEMENT training_set (alphabet, ambigs, sequence*, letter_frequencies)>
<!ATTLIST training_set primary_sequences CDATA #REQUIRED primary_count CDATA #REQUIRED primary_positions CDATA #REQUIRED
  control_sequences CDATA "" control_count CDATA "" control_positions CDATA "">
<!ELEMENT alphabet (letter*)>
<!ATTLIST alphabet name CDATA #REQUIRED>
<!ELEMENT ambigs (letter*)>
<!ELEMENT letter EMPTY>
<!ATTLIST letter id ID #REQUIRED>
<!ATTLIST letter symbol CDATA #REQUIRED>
<!ATTLIST letter equals CDATA #IMPLIED>
<!ATTLIST letter aliases CDATA #IMPLIED>
<!ATTLIST letter complement CDATA #IMPLIED>
<!ATTLIST letter name CDATA #IMPLIED>
<!ATTLIST letter colour CDATA #IMPLIED>
<!ELEMENT sequence EMPTY>
<!ATTLIST sequence id ID #REQUIRED
                   name CDATA #REQUIRED
                   length CDATA #REQUIRED
                   weight CDATA #REQUIRED
>
<!ELEMENT letter_frequencies (alphabet_array)>

<!-- Model elements -->
<!ELEMENT model (
  command_line,
  host,
  type,
  nmotifs,
  evalue_threshold,
  object_function,
  spfun,
  min_width,
  max_width,
  wg,
  ws,
  endgaps,
  minsites,
  maxsites,
  wnsites,
  spmap,
  spfuzz,
  prior,
  beta,
  maxiter,
  distance,
  num_positions,
  seed,
  hsfrac,
  searchsize,
  maxsize,
  norand,
  csites,
  strands,
  brief,
  psp_file,
  priors_file,
  reason_for_stopping,
  background_frequencies
)>
<!ELEMENT command_line (#PCDATA)*>
<!ELEMENT host (#PCDATA)*>
<!ELEMENT type (#PCDATA)*>
<!ELEMENT nmotifs (#PCDATA)*>
<!ELEMENT evalue_threshold (#PCDATA)*>
<!ELEMENT object_function (#PCDATA)*>
<!ELEMENT spfun (#PCDATA)*>
<!ELEMENT min_width (#PCDATA)*>
<!ELEMENT max_width (#PCDATA)*>
<!ELEMENT wg (#PCDATA)*>
<!ELEMENT ws (#PCDATA)*>
<!ELEMENT endgaps (#PCDATA)*>
<!ELEMENT minsites (#PCDATA)*>
<!ELEMENT maxsites (#PCDATA)*>
<!ELEMENT wnsites (#PCDATA)*>
<!ELEMENT spmap (#PCDATA)*>
<!ELEMENT spfuzz (#PCDATA)*>
<!ELEMENT prior (#PCDATA)*>
<!ELEMENT beta (#PCDATA)*>
<!ELEMENT maxiter (#PCDATA)*>
<!ELEMENT distance (#PCDATA)*>
<!ELEMENT num_positions (#PCDATA)*>
<!ELEMENT seed (#PCDATA)*>
<!ELEMENT hsfrac (#PCDATA)*>
<!ELEMENT searchsize (#PCDATA)*>
<!ELEMENT maxsize (#PCDATA)*>
<!ELEMENT norand (#PCDATA)*>
<!ELEMENT csites (#PCDATA)*>
<!ELEMENT strands (#PCDATA)*>
<!ELEMENT brief (#PCDATA)*>
<!ELEMENT psp_file (#PCDATA)*>
<!ELEMENT priors_file (#PCDATA)*>
<!ELEMENT reason_for_stopping (#PCDATA)*>
<!ELEMENT background_frequencies (alphabet_array)>
<!ATTLIST background_frequencies source CDATA #REQUIRED
		   order CDATA #REQUIRED>

<!-- Motif elements -->
<!ELEMENT motifs (motif*)>
<!ELEMENT motif (scores, probabilities, regular_expression?, contributing_sites)>
<!ATTLIST motif id ID #REQUIRED
                name CDATA #REQUIRED
                alt CDATA ""
                width CDATA #REQUIRED
                sites CDATA #REQUIRED
                ic CDATA #REQUIRED
                re CDATA #REQUIRED
                llr CDATA #REQUIRED
                p_value CDATA #REQUIRED
                e_value CDATA #REQUIRED
                bayes_threshold CDATA #REQUIRED
                elapsed_time CDATA #REQUIRED
                url CDATA ""
>
<!ELEMENT scores (alphabet_matrix)>
<!ELEMENT probabilities (alphabet_matrix)>
<!ELEMENT regular_expression (#PCDATA)*>

<!-- Contributing site elements -->
<!-- Contributing sites are motif occurences found during the motif discovery phase -->
<!ELEMENT contributing_sites (contributing_site*)>
<!ELEMENT contributing_site (left_flank, site, right_flank)>
<!ATTLIST contributing_site sequence_id IDREF #REQUIRED
                          position CDATA #REQUIRED
                          strand (plus|minus|none) 'none'
                          pvalue CDATA #REQUIRED
>
<!-- The left_flank contains the sequence for 10 bases to the left of the motif start -->
<!ELEMENT left_flank (#PCDATA)>
<!-- The site contains the sequence for the motif instance -->
<!ELEMENT site (letter_ref*)>
<!-- The right_flank contains the sequence for 10 bases to the right of the motif end -->
<!ELEMENT right_flank (#PCDATA)>

<!-- Scanned site elements -->
<!-- Scanned sites are motif occurences found during the sequence scan phase -->
<!ELEMENT scanned_sites_summary (scanned_sites*)>
<!ATTLIST scanned_sites_summary p_thresh CDATA #REQUIRED>
<!ELEMENT scanned_sites (scanned_site*)>
<!ATTLIST scanned_sites sequence_id IDREF #REQUIRED
                        pvalue CDATA #REQUIRED
                        num_sites CDATA #REQUIRED>
<!ELEMENT scanned_site EMPTY>
<!ATTLIST scanned_site  motif_id IDREF #REQUIRED
                        strand (plus|minus|none) 'none'
                        position CDATA #REQUIRED
                        pvalue CDATA #REQUIRED>

<!-- Utility elements -->
<!-- A reference to a letter in the alphabet -->
<!ELEMENT letter_ref EMPTY>
<!ATTLIST letter_ref letter_id IDREF #REQUIRED>
<!-- A alphabet-array contains one floating point value for each letter in an alphabet -->
<!ELEMENT alphabet_array (value*)>
<!ELEMENT value (#PCDATA)>
<!ATTLIST value letter_id IDREF #REQUIRED>

<!-- A alphabet_matrix contains one alphabet_array for each position in a motif -->
<!ELEMENT alphabet_matrix (alphabet_array*)>

]>
<!-- Begin document body -->
<MEME version="5.5.4" release="Fri Jun 16 12:19:08 2023 -0700">
<training_set primary_sequences="/home/hanzequan/test_bectiral/operator_recongize/all_tree/Branch_918/Layer_1_concatenated.fasta" primary_count="1" primary_positions="2388" control_sequences="--none--" control_count="0" control_positions="0">
<alphabet name="DNA" like="dna">
<letter id="A" symbol="A" complement="T" name="Adenine" colour="CC0000"/>
<letter id="C" symbol="C" complement="G" name="Cytosine" colour="0000CC"/>
<letter id="G" symbol="G" complement="C" name="Guanine" colour="FFB300"/>
<letter id="T" symbol="T" aliases="U" complement="A" name="Thymine" colour="008000"/>
<letter id="N" symbol="N" aliases="X." equals="ACGT" name="Any base"/>
<letter id="V" symbol="V" equals="ACG" name="Not T"/>
<letter id="H" symbol="H" equals="ACT" name="Not G"/>
<letter id="D" symbol="D" equals="AGT" name="Not C"/>
<letter id="B" symbol="B" equals="CGT" name="Not A"/>
<letter id="M" symbol="M" equals="AC" name="Amino"/>
<letter id="R" symbol="R" equals="AG" name="Purine"/>
<letter id="W" symbol="W" equals="AT" name="Weak"/>
<letter id="S" symbol="S" equals="CG" name="Strong"/>
<letter id="Y" symbol="Y" equals="CT" name="Pyrimidine"/>
<letter id="K" symbol="K" equals="GT" name="Keto"/>
</alphabet>
<sequence id="sequence_0" name="concatenated_intergenic_regions" length="2388" weight="1.000000" />
<letter_frequencies>
<alphabet_array>
<value letter_id="A">0.353</value>
<value letter_id="C">0.147</value>
<value letter_id="G">0.147</value>
<value letter_id="T">0.353</value>
</alphabet_array>
</letter_frequencies>
</training_set>
<model>
<command_line>meme /home/hanzequan/test_bectiral/operator_recongize/all_tree/Branch_918/Layer_1_concatenated.fasta -dna -revcomp -oc /home/hanzequan/test_bectiral/operator_recongize/all_tree/Branch_918/Layer_1 -mod anr -minw 8 -maxw 16 -nmotifs 3 -searchsize 400000 -minsites 12 -maxsites 60 </command_line>
<host>localhost.localdomain</host>
<type>anr</type>
<nmotifs>3</nmotifs>
<evalue_threshold>inf</evalue_threshold>
<object_function>E-value of product of p-values</object_function>
<spfun>E-value of product of p-values</spfun>
<min_width>8</min_width>
<max_width>16</max_width>
<wg>11</wg>
<ws>1</ws>
<endgaps>yes</endgaps>
<substring>yes</substring>
<minsites>12</minsites>
<maxsites>60</maxsites>
<wnsites>0.8</wnsites>
<spmap>uni</spmap>
<spfuzz>0.5</spfuzz>
<prior>dirichlet</prior>
<beta>0.01</beta>
<maxiter>50</maxiter>
<distance>1e-05</distance>
<num_positions>2388</num_positions>
<seed>0</seed>
<hsfrac>0</hsfrac>
<searchsize>2388</searchsize>
<maxsize>0</maxsize>
<norand>no</norand>
<csites>1000</csites>
<strands>both</strands>
<brief>1000</brief>
<psp_file></psp_file>
<priors_file></priors_file>
<reason_for_stopping>Stopped because requested number of motifs (3) found.</reason_for_stopping>
<background_frequencies source="--sequences--" order="0">
<alphabet_array>
<value letter_id="A">0.353</value>
<value letter_id="C">0.147</value>
<value letter_id="G">0.147</value>
<value letter_id="T">0.353</value>
</alphabet_array>
</background_frequencies>
</model>
<motifs>
<motif id="motif_1" name="YTBWTTBTTCYCTCCT" alt="MEME-1" width="16" sites="34" ic="13.2" re="14.5" llr="342" p_value="3.2e-114" e_value="8.0e-028" bayes_threshold="5.40269" elapsed_time="1.361501">
<scores>
<alphabet_matrix>
<alphabet_array>
<value letter_id="A">-100</value>
<value letter_id="C">149</value>
<value letter_id="G">-132</value>
<value letter_id="T">0</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-200</value>
<value letter_id="C">-74</value>
<value letter_id="G">-74</value>
<value letter_id="T">106</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-200</value>
<value letter_id="C">138</value>
<value letter_id="G">100</value>
<value letter_id="T">-59</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">41</value>
<value letter_id="C">-1173</value>
<value letter_id="G">68</value>
<value letter_id="T">-26</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-78</value>
<value letter_id="C">-1173</value>
<value letter_id="G">-132</value>
<value letter_id="T">106</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-59</value>
<value letter_id="C">-32</value>
<value letter_id="G">0</value>
<value letter_id="T">50</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-126</value>
<value letter_id="C">49</value>
<value letter_id="G">114</value>
<value letter_id="T">-13</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-78</value>
<value letter_id="C">49</value>
<value letter_id="G">-1173</value>
<value letter_id="T">74</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-258</value>
<value letter_id="C">85</value>
<value letter_id="G">-1173</value>
<value letter_id="T">94</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-59</value>
<value letter_id="C">193</value>
<value letter_id="G">-132</value>
<value letter_id="T">-126</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-1173</value>
<value letter_id="C">207</value>
<value letter_id="G">-132</value>
<value letter_id="T">-13</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-1173</value>
<value letter_id="C">277</value>
<value letter_id="G">-1173</value>
<value letter_id="T">-1173</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-1173</value>
<value letter_id="C">-74</value>
<value letter_id="G">-1173</value>
<value letter_id="T">137</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-1173</value>
<value letter_id="C">277</value>
<value letter_id="G">-1173</value>
<value letter_id="T">-1173</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-158</value>
<value letter_id="C">238</value>
<value letter_id="G">-132</value>
<value letter_id="T">-258</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-1173</value>
<value letter_id="C">85</value>
<value letter_id="G">-1173</value>
<value letter_id="T">106</value>
</alphabet_array>
</alphabet_matrix>
</scores>
<probabilities>
<alphabet_matrix>
<alphabet_array>
<value letter_id="A">0.176471</value>
<value letter_id="C">0.411765</value>
<value letter_id="G">0.058824</value>
<value letter_id="T">0.352941</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.088235</value>
<value letter_id="C">0.088235</value>
<value letter_id="G">0.088235</value>
<value letter_id="T">0.735294</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.088235</value>
<value letter_id="C">0.382353</value>
<value letter_id="G">0.294118</value>
<value letter_id="T">0.235294</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.470588</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">0.235294</value>
<value letter_id="T">0.294118</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.205882</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">0.058824</value>
<value letter_id="T">0.735294</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.235294</value>
<value letter_id="C">0.117647</value>
<value letter_id="G">0.147059</value>
<value letter_id="T">0.500000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.147059</value>
<value letter_id="C">0.205882</value>
<value letter_id="G">0.323529</value>
<value letter_id="T">0.323529</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.205882</value>
<value letter_id="C">0.205882</value>
<value letter_id="G">0.000000</value>
<value letter_id="T">0.588235</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.058824</value>
<value letter_id="C">0.264706</value>
<value letter_id="G">0.000000</value>
<value letter_id="T">0.676471</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.235294</value>
<value letter_id="C">0.558824</value>
<value letter_id="G">0.058824</value>
<value letter_id="T">0.147059</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.000000</value>
<value letter_id="C">0.617647</value>
<value letter_id="G">0.058824</value>
<value letter_id="T">0.323529</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.000000</value>
<value letter_id="C">1.000000</value>
<value letter_id="G">0.000000</value>
<value letter_id="T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.000000</value>
<value letter_id="C">0.088235</value>
<value letter_id="G">0.000000</value>
<value letter_id="T">0.911765</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.000000</value>
<value letter_id="C">1.000000</value>
<value letter_id="G">0.000000</value>
<value letter_id="T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.117647</value>
<value letter_id="C">0.764706</value>
<value letter_id="G">0.058824</value>
<value letter_id="T">0.058824</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.000000</value>
<value letter_id="C">0.264706</value>
<value letter_id="G">0.000000</value>
<value letter_id="T">0.735294</value>
</alphabet_array>
</alphabet_matrix>
</probabilities>
<regular_expression>
[CT]T[CGT][ATG][TA][TA][GTC][TAC][TC][CA][CT]CTCC[TC]
</regular_expression>
<contributing_sites>
<contributing_site sequence_id="sequence_0" position="1673" strand="plus" pvalue="8.96e-10" >
<left_flank>AAGTGTAAAA</left_flank>
<site>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
</site>
<right_flank>TAAATTCTAG</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_0" position="162" strand="minus" pvalue="1.65e-08" >
<left_flank>TCAATTAGTG</left_flank>
<site>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
</site>
<right_flank>TAACTTTCTA</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_0" position="2162" strand="plus" pvalue="6.34e-08" >
<left_flank>TTTAACTTTC</left_flank>
<site>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
</site>
<right_flank>TAACTTTCTA</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_0" position="1481" strand="minus" pvalue="6.34e-08" >
<left_flank>TATGTATCTC</left_flank>
<site>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
</site>
<right_flank>TGCTTTTTGA</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_0" position="555" strand="plus" pvalue="6.34e-08" >
<left_flank>TATGTATCTC</left_flank>
<site>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
</site>
<right_flank>TGCTTTTTGA</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_0" position="316" strand="minus" pvalue="1.33e-06" >
<left_flank>CTTTGTTTAC</left_flank>
<site>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
</site>
<right_flank>GTTGTAACCT</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_0" position="1851" strand="plus" pvalue="1.94e-06" >
<left_flank>TAATTCTTTC</left_flank>
<site>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
</site>
<right_flank>GATATATATA</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_0" position="1549" strand="plus" pvalue="2.48e-06" >
<left_flank>ATTATCAAGG</left_flank>
<site>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
</site>
<right_flank>ACCGGTGGGG</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_0" position="455" strand="minus" pvalue="2.48e-06" >
<left_flank>ATTATCAAGG</left_flank>
<site>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
</site>
<right_flank>ACCGGTGGGG</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_0" position="1054" strand="plus" pvalue="2.79e-06" >
<left_flank>GGCACACAAA</left_flank>
<site>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
</site>
<right_flank>CAAATTCTAA</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_0" position="1571" strand="minus" pvalue="3.15e-06" >
<left_flank>AGAAAATTAA</left_flank>
<site>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
</site>
<right_flank>ACCGGTAGGG</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_0" position="431" strand="plus" pvalue="3.53e-06" >
<left_flank>AGAAAATAAA</left_flank>
<site>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
</site>
<right_flank>CCACCGGTAG</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_0" position="2290" strand="minus" pvalue="5.56e-06" >
<left_flank>TTATCATTTT</left_flank>
<site>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
</site>
<right_flank>AATTATTAAC</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_0" position="1899" strand="minus" pvalue="5.56e-06" >
<left_flank>TTATTGAACT</left_flank>
<site>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
</site>
<right_flank>TTTTCTTTTA</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_0" position="1114" strand="plus" pvalue="5.56e-06" >
<left_flank>TTATCATTTT</left_flank>
<site>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
</site>
<right_flank>ATTAAAAAAA</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_0" position="1991" strand="plus" pvalue="8.50e-06" >
<left_flank>ATCAGTTATT</left_flank>
<site>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
</site>
<right_flank>TAAATGTATT</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_0" position="962" strand="minus" pvalue="8.50e-06" >
<left_flank>TTATCATATT</left_flank>
<site>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
</site>
<right_flank>ATTAGAAAAA</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_0" position="1296" strand="minus" pvalue="9.45e-06" >
<left_flank>ATAGTATAAC</left_flank>
<site>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
</site>
<right_flank>TTCATAATAT</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_0" position="727" strand="plus" pvalue="9.45e-06" >
<left_flank>ATAGCTTGAC</left_flank>
<site>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
</site>
<right_flank>TTCATAATAT</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_0" position="13" strand="plus" pvalue="9.45e-06" >
<left_flank>GGCACACAAA</left_flank>
<site>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
</site>
<right_flank>CAAATTCTAA</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_0" position="1604" strand="plus" pvalue="1.05e-05" >
<left_flank>TCTAATTGTT</left_flank>
<site>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
</site>
<right_flank>TTAACCTTAT</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_0" position="1387" strand="minus" pvalue="1.16e-05" >
<left_flank>CCTCCTTGTG</left_flank>
<site>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
</site>
<right_flank>TTAATTTCTT</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_0" position="636" strand="plus" pvalue="1.16e-05" >
<left_flank>ACCTCCTTGA</left_flank>
<site>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
</site>
<right_flank>TTAATTTCTT</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_0" position="398" strand="minus" pvalue="1.55e-05" >
<left_flank>TCTAATTGTT</left_flank>
<site>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>