<?xml version='1.0' encoding='UTF-8' standalone='yes'?>
<!-- Document definition -->
<!DOCTYPE MEME[
<!ELEMENT MEME (
  training_set,
  model, 
  motifs, 
  scanned_sites_summary?
)>
<!ATTLIST MEME 
  version CDATA #REQUIRED
  release CDATA #REQUIRED
>
<!-- Training-set elements -->
<!ELEMENT training_set (alphabet, ambigs, sequence*, letter_frequencies)>
<!ATTLIST training_set primary_sequences CDATA #REQUIRED primary_count CDATA #REQUIRED primary_positions CDATA #REQUIRED
  control_sequences CDATA "" control_count CDATA "" control_positions CDATA "">
<!ELEMENT alphabet (letter*)>
<!ATTLIST alphabet name CDATA #REQUIRED>
<!ELEMENT ambigs (letter*)>
<!ELEMENT letter EMPTY>
<!ATTLIST letter id ID #REQUIRED>
<!ATTLIST letter symbol CDATA #REQUIRED>
<!ATTLIST letter equals CDATA #IMPLIED>
<!ATTLIST letter aliases CDATA #IMPLIED>
<!ATTLIST letter complement CDATA #IMPLIED>
<!ATTLIST letter name CDATA #IMPLIED>
<!ATTLIST letter colour CDATA #IMPLIED>
<!ELEMENT sequence EMPTY>
<!ATTLIST sequence id ID #REQUIRED
                   name CDATA #REQUIRED
                   length CDATA #REQUIRED
                   weight CDATA #REQUIRED
>
<!ELEMENT letter_frequencies (alphabet_array)>

<!-- Model elements -->
<!ELEMENT model (
  command_line,
  host,
  type,
  nmotifs,
  evalue_threshold,
  object_function,
  spfun,
  min_width,
  max_width,
  wg,
  ws,
  endgaps,
  minsites,
  maxsites,
  wnsites,
  spmap,
  spfuzz,
  prior,
  beta,
  maxiter,
  distance,
  num_positions,
  seed,
  hsfrac,
  searchsize,
  maxsize,
  norand,
  csites,
  strands,
  brief,
  psp_file,
  priors_file,
  reason_for_stopping,
  background_frequencies
)>
<!ELEMENT command_line (#PCDATA)*>
<!ELEMENT host (#PCDATA)*>
<!ELEMENT type (#PCDATA)*>
<!ELEMENT nmotifs (#PCDATA)*>
<!ELEMENT evalue_threshold (#PCDATA)*>
<!ELEMENT object_function (#PCDATA)*>
<!ELEMENT spfun (#PCDATA)*>
<!ELEMENT min_width (#PCDATA)*>
<!ELEMENT max_width (#PCDATA)*>
<!ELEMENT wg (#PCDATA)*>
<!ELEMENT ws (#PCDATA)*>
<!ELEMENT endgaps (#PCDATA)*>
<!ELEMENT minsites (#PCDATA)*>
<!ELEMENT maxsites (#PCDATA)*>
<!ELEMENT wnsites (#PCDATA)*>
<!ELEMENT spmap (#PCDATA)*>
<!ELEMENT spfuzz (#PCDATA)*>
<!ELEMENT prior (#PCDATA)*>
<!ELEMENT beta (#PCDATA)*>
<!ELEMENT maxiter (#PCDATA)*>
<!ELEMENT distance (#PCDATA)*>
<!ELEMENT num_positions (#PCDATA)*>
<!ELEMENT seed (#PCDATA)*>
<!ELEMENT hsfrac (#PCDATA)*>
<!ELEMENT searchsize (#PCDATA)*>
<!ELEMENT maxsize (#PCDATA)*>
<!ELEMENT norand (#PCDATA)*>
<!ELEMENT csites (#PCDATA)*>
<!ELEMENT strands (#PCDATA)*>
<!ELEMENT brief (#PCDATA)*>
<!ELEMENT psp_file (#PCDATA)*>
<!ELEMENT priors_file (#PCDATA)*>
<!ELEMENT reason_for_stopping (#PCDATA)*>
<!ELEMENT background_frequencies (alphabet_array)>
<!ATTLIST background_frequencies source CDATA #REQUIRED
		   order CDATA #REQUIRED>

<!-- Motif elements -->
<!ELEMENT motifs (motif*)>
<!ELEMENT motif (scores, probabilities, regular_expression?, contributing_sites)>
<!ATTLIST motif id ID #REQUIRED
                name CDATA #REQUIRED
                alt CDATA ""
                width CDATA #REQUIRED
                sites CDATA #REQUIRED
                ic CDATA #REQUIRED
                re CDATA #REQUIRED
                llr CDATA #REQUIRED
                p_value CDATA #REQUIRED
                e_value CDATA #REQUIRED
                bayes_threshold CDATA #REQUIRED
                elapsed_time CDATA #REQUIRED
                url CDATA ""
>
<!ELEMENT scores (alphabet_matrix)>
<!ELEMENT probabilities (alphabet_matrix)>
<!ELEMENT regular_expression (#PCDATA)*>

<!-- Contributing site elements -->
<!-- Contributing sites are motif occurences found during the motif discovery phase -->
<!ELEMENT contributing_sites (contributing_site*)>
<!ELEMENT contributing_site (left_flank, site, right_flank)>
<!ATTLIST contributing_site sequence_id IDREF #REQUIRED
                          position CDATA #REQUIRED
                          strand (plus|minus|none) 'none'
                          pvalue CDATA #REQUIRED
>
<!-- The left_flank contains the sequence for 10 bases to the left of the motif start -->
<!ELEMENT left_flank (#PCDATA)>
<!-- The site contains the sequence for the motif instance -->
<!ELEMENT site (letter_ref*)>
<!-- The right_flank contains the sequence for 10 bases to the right of the motif end -->
<!ELEMENT right_flank (#PCDATA)>

<!-- Scanned site elements -->
<!-- Scanned sites are motif occurences found during the sequence scan phase -->
<!ELEMENT scanned_sites_summary (scanned_sites*)>
<!ATTLIST scanned_sites_summary p_thresh CDATA #REQUIRED>
<!ELEMENT scanned_sites (scanned_site*)>
<!ATTLIST scanned_sites sequence_id IDREF #REQUIRED
                        pvalue CDATA #REQUIRED
                        num_sites CDATA #REQUIRED>
<!ELEMENT scanned_site EMPTY>
<!ATTLIST scanned_site  motif_id IDREF #REQUIRED
                        strand (plus|minus|none) 'none'
                        position CDATA #REQUIRED
                        pvalue CDATA #REQUIRED>

<!-- Utility elements -->
<!-- A reference to a letter in the alphabet -->
<!ELEMENT letter_ref EMPTY>
<!ATTLIST letter_ref letter_id IDREF #REQUIRED>
<!-- A alphabet-array contains one floating point value for each letter in an alphabet -->
<!ELEMENT alphabet_array (value*)>
<!ELEMENT value (#PCDATA)>
<!ATTLIST value letter_id IDREF #REQUIRED>

<!-- A alphabet_matrix contains one alphabet_array for each position in a motif -->
<!ELEMENT alphabet_matrix (alphabet_array*)>

]>
<!-- Begin document body -->
<MEME version="5.5.4" release="Fri Jun 16 12:19:08 2023 -0700">
<training_set primary_sequences="/home/hanzequan/test_bectiral/operator_recongize/all_tree/Branch_500/Layer_6_concatenated.fasta" primary_count="1" primary_positions="23977" control_sequences="--none--" control_count="0" control_positions="0">
<alphabet name="DNA" like="dna">
<letter id="A" symbol="A" complement="T" name="Adenine" colour="CC0000"/>
<letter id="C" symbol="C" complement="G" name="Cytosine" colour="0000CC"/>
<letter id="G" symbol="G" complement="C" name="Guanine" colour="FFB300"/>
<letter id="T" symbol="T" aliases="U" complement="A" name="Thymine" colour="008000"/>
<letter id="N" symbol="N" aliases="X." equals="ACGT" name="Any base"/>
<letter id="V" symbol="V" equals="ACG" name="Not T"/>
<letter id="H" symbol="H" equals="ACT" name="Not G"/>
<letter id="D" symbol="D" equals="AGT" name="Not C"/>
<letter id="B" symbol="B" equals="CGT" name="Not A"/>
<letter id="M" symbol="M" equals="AC" name="Amino"/>
<letter id="R" symbol="R" equals="AG" name="Purine"/>
<letter id="W" symbol="W" equals="AT" name="Weak"/>
<letter id="S" symbol="S" equals="CG" name="Strong"/>
<letter id="Y" symbol="Y" equals="CT" name="Pyrimidine"/>
<letter id="K" symbol="K" equals="GT" name="Keto"/>
</alphabet>
<sequence id="sequence_0" name="concatenated_intergenic_regions" length="23977" weight="1.000000" />
<letter_frequencies>
<alphabet_array>
<value letter_id="A">0.32</value>
<value letter_id="C">0.18</value>
<value letter_id="G">0.18</value>
<value letter_id="T">0.32</value>
</alphabet_array>
</letter_frequencies>
</training_set>
<model>
<command_line>meme /home/hanzequan/test_bectiral/operator_recongize/all_tree/Branch_500/Layer_6_concatenated.fasta -dna -revcomp -oc /home/hanzequan/test_bectiral/operator_recongize/all_tree/Branch_500/Layer_6 -mod anr -minw 8 -maxw 16 -nmotifs 3 -searchsize 400000 -minsites 15 -maxsites 75 </command_line>
<host>localhost.localdomain</host>
<type>anr</type>
<nmotifs>3</nmotifs>
<evalue_threshold>inf</evalue_threshold>
<object_function>E-value of product of p-values</object_function>
<spfun>E-value of product of p-values</spfun>
<min_width>8</min_width>
<max_width>16</max_width>
<wg>11</wg>
<ws>1</ws>
<endgaps>yes</endgaps>
<substring>yes</substring>
<minsites>15</minsites>
<maxsites>75</maxsites>
<wnsites>0.8</wnsites>
<spmap>uni</spmap>
<spfuzz>0.5</spfuzz>
<prior>dirichlet</prior>
<beta>0.01</beta>
<maxiter>50</maxiter>
<distance>1e-05</distance>
<num_positions>23977</num_positions>
<seed>0</seed>
<hsfrac>0</hsfrac>
<searchsize>23977</searchsize>
<maxsize>0</maxsize>
<norand>no</norand>
<csites>1000</csites>
<strands>both</strands>
<brief>1000</brief>
<psp_file></psp_file>
<priors_file></priors_file>
<reason_for_stopping>Stopped because requested number of motifs (3) found.</reason_for_stopping>
<background_frequencies source="--sequences--" order="0">
<alphabet_array>
<value letter_id="A">0.32</value>
<value letter_id="C">0.18</value>
<value letter_id="G">0.18</value>
<value letter_id="T">0.32</value>
</alphabet_array>
</background_frequencies>
</model>
<motifs>
<motif id="motif_1" name="TKBTSCTTTTTTWWT" alt="MEME-1" width="15" sites="75" ic="15.9" re="14.7" llr="764" p_value="7.1e-293" e_value="2.7e-051" bayes_threshold="8.56744" elapsed_time="40.359781">
<scores>
<alphabet_matrix>
<alphabet_array>
<value letter_id="A">-458</value>
<value letter_id="C">-143</value>
<value letter_id="G">49</value>
<value letter_id="T">106</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-78</value>
<value letter_id="C">-75</value>
<value letter_id="G">64</value>
<value letter_id="T">41</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-1287</value>
<value letter_id="C">83</value>
<value letter_id="G">105</value>
<value letter_id="T">-6</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-1287</value>
<value letter_id="C">-375</value>
<value letter_id="G">49</value>
<value letter_id="T">120</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-458</value>
<value letter_id="C">129</value>
<value letter_id="G">160</value>
<value letter_id="T">-1287</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-1287</value>
<value letter_id="C">246</value>
<value letter_id="G">-1287</value>
<value letter_id="T">-458</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-1287</value>
<value letter_id="C">-1287</value>
<value letter_id="G">71</value>
<value letter_id="T">114</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-1287</value>
<value letter_id="C">-275</value>
<value letter_id="G">-1287</value>
<value letter_id="T">160</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-1287</value>
<value letter_id="C">-1287</value>
<value letter_id="G">-1287</value>
<value letter_id="T">164</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-1287</value>
<value letter_id="C">5</value>
<value letter_id="G">-1287</value>
<value letter_id="T">135</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-1287</value>
<value letter_id="C">-1287</value>
<value letter_id="G">-1287</value>
<value letter_id="T">164</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-59</value>
<value letter_id="C">-375</value>
<value letter_id="G">-275</value>
<value letter_id="T">122</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">32</value>
<value letter_id="C">-175</value>
<value letter_id="G">-5</value>
<value letter_id="T">22</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-34</value>
<value letter_id="C">-5</value>
<value letter_id="G">5</value>
<value letter_id="T">27</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-458</value>
<value letter_id="C">33</value>
<value letter_id="G">-375</value>
<value letter_id="T">122</value>
</alphabet_array>
</alphabet_matrix>
</scores>
<probabilities>
<alphabet_matrix>
<alphabet_array>
<value letter_id="A">0.013333</value>
<value letter_id="C">0.066667</value>
<value letter_id="G">0.253333</value>
<value letter_id="T">0.666667</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.186667</value>
<value letter_id="C">0.106667</value>
<value letter_id="G">0.280000</value>
<value letter_id="T">0.426667</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.000000</value>
<value letter_id="C">0.320000</value>
<value letter_id="G">0.373333</value>
<value letter_id="T">0.306667</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.000000</value>
<value letter_id="C">0.013333</value>
<value letter_id="G">0.253333</value>
<value letter_id="T">0.733333</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.013333</value>
<value letter_id="C">0.440000</value>
<value letter_id="G">0.546667</value>
<value letter_id="T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.000000</value>
<value letter_id="C">0.986667</value>
<value letter_id="G">0.000000</value>
<value letter_id="T">0.013333</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.000000</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">0.293333</value>
<value letter_id="T">0.706667</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.000000</value>
<value letter_id="C">0.026667</value>
<value letter_id="G">0.000000</value>
<value letter_id="T">0.973333</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.000000</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">0.000000</value>
<value letter_id="T">1.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.000000</value>
<value letter_id="C">0.186667</value>
<value letter_id="G">0.000000</value>
<value letter_id="T">0.813333</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.000000</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">0.000000</value>
<value letter_id="T">1.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.213333</value>
<value letter_id="C">0.013333</value>
<value letter_id="G">0.026667</value>
<value letter_id="T">0.746667</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.400000</value>
<value letter_id="C">0.053333</value>
<value letter_id="G">0.173333</value>
<value letter_id="T">0.373333</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.253333</value>
<value letter_id="C">0.173333</value>
<value letter_id="G">0.186667</value>
<value letter_id="T">0.386667</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.013333</value>
<value letter_id="C">0.226667</value>
<value letter_id="G">0.013333</value>
<value letter_id="T">0.746667</value>
</alphabet_array>
</alphabet_matrix>
</probabilities>
<regular_expression>
[TG][TG][GCT][TG][GC]C[TG]TTTT[TA][AT][TA][TC]
</regular_expression>
<contributing_sites>
<contributing_site sequence_id="sequence_0" position="13595" strand="plus" pvalue="3.78e-09" >
<left_flank>AGCACCGAAT</left_flank>
<site>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
</site>
<right_flank>ACCAGAAAGG</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_0" position="7992" strand="plus" pvalue="3.78e-09" >
<left_flank>AGCACCGAAT</left_flank>
<site>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
</site>
<right_flank>ACCAGAAAGG</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_0" position="22419" strand="plus" pvalue="2.22e-07" >
<left_flank>ATCTAAATGA</left_flank>
<site>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
</site>
<right_flank>ACCCAAAAAG</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_0" position="17567" strand="plus" pvalue="2.22e-07" >
<left_flank>ATCTAAATGA</left_flank>
<site>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
</site>
<right_flank>ACCCAAAAAG</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_0" position="11385" strand="minus" pvalue="5.93e-07" >
<left_flank>AGAAGCTAAG</left_flank>
<site>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
</site>
<right_flank>ATAATGTAAG</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_0" position="5711" strand="minus" pvalue="5.93e-07" >
<left_flank>AGAAGCTAAG</left_flank>
<site>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
</site>
<right_flank>ATAATGTAAG</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_0" position="18670" strand="plus" pvalue="1.29e-06" >
<left_flank>TAGCGTGAGC</left_flank>
<site>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
</site>
<right_flank>TTCCAAATTA</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_0" position="22264" strand="plus" pvalue="1.60e-06" >
<left_flank>CACACGTTCG</left_flank>
<site>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
</site>
<right_flank>TTATTTGATT</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_0" position="17440" strand="plus" pvalue="1.60e-06" >
<left_flank>CACACATTTG</left_flank>
<site>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
</site>
<right_flank>TTATTTGATT</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_0" position="15075" strand="plus" pvalue="1.60e-06" >
<left_flank>AAATTTGAGC</left_flank>
<site>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
</site>
<right_flank>AGTTTAACCT</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_0" position="23779" strand="plus" pvalue="1.99e-06" >
<left_flank>TAGCGCGAGC</left_flank>
<site>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
</site>
<right_flank>TTCCAAATTA</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_0" position="23652" strand="plus" pvalue="1.99e-06" >
<left_flank>TTTGATGGCT</left_flank>
<site>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
</site>
<right_flank>ATAATAGACA</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_0" position="14459" strand="plus" pvalue="2.39e-06" >
<left_flank>CGGCTTTGCT</left_flank>
<site>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
</site>
<right_flank>TATTATATAA</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_0" position="10581" strand="minus" pvalue="2.39e-06" >
<left_flank>TAAATCCTCG</left_flank>
<site>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
</site>
<right_flank>ACATCTATTT</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_0" position="8856" strand="plus" pvalue="2.39e-06" >
<left_flank>CGGCTTTGCT</left_flank>
<site>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
</site>
<right_flank>TATTATATAA</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_0" position="4907" strand="minus" pvalue="2.39e-06" >
<left_flank>TAAATCCTCG</left_flank>
<site>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
</site>
<right_flank>ACATCTATTT</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_0" position="1119" strand="minus" pvalue="2.39e-06" >
<left_flank>ACTGTTTGTT</left_flank>
<site>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
</site>
<right_flank>GCGGATTCTC</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_0" position="13969" strand="plus" pvalue="3.39e-06" >
<left_flank>TCGTATTTTA</left_flank>
<site>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
</site>
<right_flank>TTGGAAGATT</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_0" position="8366" strand="plus" pvalue="3.39e-06" >
<left_flank>TCGTATTTTA</left_flank>
<site>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
</site>
<right_flank>TTGGAAGATT</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_0" position="2958" strand="minus" pvalue="3.39e-06" >
<left_flank>TATTTGTTAG</left_flank>
<site>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
</site>
<right_flank>CCTTTCGAAT</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_0" position="9950" strand="minus" pvalue="3.97e-06" >
<left_flank>GTAGGAGATA</left_flank>
<site>
<letter_ref letter_id="G"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
</site>
<right_flank>TGCGAAGGTA</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_0" position="4276" strand="minus" pvalue="3.97e-06" >
<left_flank>GTAGGAGATA</left_flank>
<site>
<letter_ref letter_id="G"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
</site>
<right_flank>TGCGAAGGTA</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_0" position="22823" strand="minus" pvalue="4.63e-06" >
<left_flank>CTGAATTTAA</left_flank>
<site>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
</site>
<right_flank>TTTCCGCATA</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_0" position="17969" strand="minus" pvalue="4.63e-06" >
<left_flank>CTCTGGATAA</left_flank>
<site>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
</site>
<right_flank>TTTGCATAAA</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_0" position="2988" strand="plus" pvalue="4.63e-06" >
<left_flank>AAATAGGTTA</left_flank>
<site>
<letter_ref letter_id="G"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
</site>
<right_flank>ACCCAAAAAT</right_flank>
</contributing_site>